<?php
define('_JEXEC', 1);
require_once 'communicator.php';
require_once 'backlinkvalidator.php';
require_once 'link.php';
/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-09-10 at 17:24:41.
 */
class BacklinkValidatorTest extends PHPUnit_Framework_TestCase {

    /**
     * @var BacklinkValidator
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $link = new Link('http://www.stilero.com/', 'Stilero webdesign');
        $linker = new Link('http://www.stilero.com');
        $this->object = new BacklinkValidator($link, $linker);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        unset($this->object);
    }

    /**
     * @covers BacklinkValidator::check
     * @todo   Implement testCheck().
     */
    public function testCheck() {
        $this->assertTrue($this->object->check());
    }

    /**
     * @covers BacklinkValidator::isFound
     * @todo   Implement testIsFound().
     */
    public function testIsFound() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
