<?php
define('_JEXEC', 1);
/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-09-10 at 17:24:07.
 */
class CommunicatorTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Communicator
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Communicator;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Communicator::query
     * @todo   Implement testQuery().
     */
    public function testQuery() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Communicator::setUrl
     * @todo   Implement testSetUrl().
     */
    public function testSetUrl() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Communicator::setHeader
     * @todo   Implement testSetHeader().
     */
    public function testSetHeader() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Communicator::setPostVars
     * @todo   Implement testSetPostVars().
     */
    public function testSetPostVars() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Communicator::getResponse
     * @todo   Implement testGetResponse().
     */
    public function testGetResponse() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Communicator::getInfo
     * @todo   Implement testGetInfo().
     */
    public function testGetInfo() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Communicator::getInfoHTTPCode
     * @todo   Implement testGetInfoHTTPCode().
     */
    public function testGetInfoHTTPCode() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Communicator::isOK
     * @todo   Implement testIsOK().
     */
    public function testIsOK() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
