<?php
define('_JEXEC', 1);
require_once '../communicator.php';
/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-09-27 at 12:43:38.
 */
class CommunicatorTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Communicator
     */
    protected $object;
    protected $url;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->url = 'http://www.stilero.com';
        $this->object = new Communicator($this->url);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        unset($this->object);
    }

    public function testQueryFound() {
        $url = "http://www.stilero.com/";
        $this->object->setUrl($url);
        $this->object->query();
        $isOK = $this->object->isOK();
        $this->assertTrue($isOK, 'Status code: '.$this->object->getInfoHTTPCode());
    }
    
    /**
     * @covers Communicator::query
     * @todo   Implement testQuery().
     */
    public function testQueryNotFound() {
        $url = "http://www.sdflkjsdflkjnv.com";
        $this->object->setUrl($url);
        $this->object->query();
        $isOK = $this->object->isOK();
        $this->assertFalse($isOK);
    }
    
    /**
     * @covers Communicator::setUrl
     * @todo   Implement testSetUrl().
     */
    public function testSetUrl() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Communicator::setHeader
     * @todo   Implement testSetHeader().
     */
    public function testSetHeader() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Communicator::setPostVars
     * @todo   Implement testSetPostVars().
     */
    public function testSetPostVars() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Communicator::getResponse
     * @todo   Implement testGetResponse().
     */
    public function testGetResponse() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Communicator::getInfo
     * @todo   Implement testGetInfo().
     */
    public function testGetInfo() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Communicator::getInfoHTTPCode
     * @todo   Implement testGetInfoHTTPCode().
     */
    public function testGetInfoHTTPCode() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Communicator::isOK
     * @todo   Implement testIsOK().
     */
    public function testIsOK() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Communicator::__get
     * @todo   Implement test__get().
     */
    public function test__get() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Communicator::__set
     * @todo   Implement test__set().
     */
    public function test__set() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
