<?php
define('_JEXEC', 1);
/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-09-10 at 17:24:06.
 */
class LinkTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Link
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Link;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Link::isNoFollow
     * @todo   Implement testIsNoFollow().
     */
    public function testIsNoFollow() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Link::baseURL
     * @todo   Implement testBaseURL().
     */
    public function testBaseURL() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Link::queryVars
     * @todo   Implement testQueryVars().
     */
    public function testQueryVars() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
